service: teleology-oauth2-example

plugins:
  - serverless-plugin-modularize
  - serverless-offline

custom:
  modularize:
    glob: 'src/**/*.module.yml'

provider:
  name: aws
  runtime: nodejs12.x
